# https://medium.com/@aharon.amir/develop-c-on-docker-with-vscode-98fb85b818b2
version: '2'
services:
  dev-image:
    image: eagle1/armv7/develop
    privileged: true
    container_name: armv7-devenv
    volumes:
      - "./:/home/develop/eagle"